include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    discarded_futures: ignore
  exclude:
    - lib/src/lucide_icons.dart