library;

import 'package:flutter/foundation.dart';
import 'package:flutter/painting.dart';

@immutable
class TextTheme {
  const TextTheme({
    required this.h1,
    required this.h2,
    required this.h3,
    required this.h4,
    required this.p,
    required this.blockquote,
    required this.table,
    required this.list,
    required this.inlineCode,
    required this.lead,
    required this.large,
    required this.small,
    required this.muted,
  });

  final TextStyle h1;
  final TextStyle h2;
  final TextStyle h3;
  final TextStyle h4;
  final TextStyle p;
  final TextStyle blockquote;
  final TextStyle table;
  final TextStyle list;
  final TextStyle inlineCode;
  final TextStyle lead;
  final TextStyle large;
  final TextStyle small;
  final TextStyle muted;

  TextTheme apply({
    String? fontFamily,
    List<String>? fontFamilyFallback,
    String? package,
    double fontSizeFactor = 1.0,
    double fontSizeDelta = 0.0,
    double letterSpacingFactor = 1.0,
    double letterSpacingDelta = 0.0,
    double wordSpacingFactor = 1.0,
    double wordSpacingDelta = 0.0,
    double heightFactor = 1.0,
    double heightDelta = 0.0,
    Color? displayColor,
    Color? bodyColor,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
  }) {
    return TextTheme(
      h1: h1.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      h2: h2.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      h3: h3.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      h4: h4.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      p: p.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      blockquote: blockquote.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      table: table.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      list: list.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      inlineCode: inlineCode.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      lead: lead.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      large: large.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      small: small.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
      muted: muted.apply(
        color: displayColor,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSizeFactor: fontSizeFactor,
        fontSizeDelta: fontSizeDelta,
        letterSpacingDelta: letterSpacingDelta,
        letterSpacingFactor: letterSpacingFactor,
        wordSpacingDelta: wordSpacingDelta,
        wordSpacingFactor: wordSpacingFactor,
        heightFactor: heightFactor,
        heightDelta: heightDelta,
        package: package,
      ),
    );
  }
}
